import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import  bgImg  from '../public/allosunshine.png'
import Link from 'next/link'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>ALLÔSUNSHINE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
      
      <div className='flex items-center justify-center h-screen'>
        {/*overlay*/} 
        
        <div/>
        <div className=''>
        
            <Image src={bgImg} alt='/' priority />
           <div className='flex items-center justify-center ml-[-3%] pl-4 w-full '>
          <Link href='/enabout'>
            <button className='mr-2'>EN</button> 
          </Link> 
          <Link href='/about'>
          <button>FR</button>
          </Link>
           </div>
        </div>
        <Footer />
    </div>
    </>
  )
}
